import type { DesktopApi } from "../../shared/desktop-api";

/** Workspace data, replica crypto, and realtime only. Session and application services stay in App. */
export type WorkspaceClient = Pick<
  DesktopApi,
  | "acknowledgeWorkspaceEvent"
  | "activateWorkspaceRealtime"
  | "addMessageReaction"
  | "advanceReadCursor"
  | "archiveChannel"
  | "chooseAndUploadConversationFiles"
  | "createChannel"
  | "createDirectConversation"
  | "createTask"
  | "decryptCacheRecords"
  | "encryptCacheRecords"
  | "getChannelMembers"
  | "getConversationMessages"
  | "getMessageById"
  | "getMessageThread"
  | "getWorkspaceBootstrap"
  | "initializeCacheCrypto"
  | "listConversationFiles"
  | "listConversationTasks"
  | "listConversations"
  | "listMessageAttachments"
  | "listMessageReactions"
  | "listMyTasks"
  | "listWorkspaceMembers"
  | "moveTask"
  | "onRealtimeStateChanged"
  | "onWorkspaceActivity"
  | "onWorkspaceEvent"
  | "openConversationFile"
  | "removeChannelMember"
  | "removeMessageReaction"
  | "resetCacheCrypto"
  | "retractMessage"
  | "searchMessages"
  | "sendConversationMessage"
  | "setWorkspaceTyping"
  | "startWorkspaceRealtime"
  | "stopWorkspaceRealtime"
  | "syncWorkspace"
  | "updateProfile"
  | "updateTask"
  | "upsertChannelMember"
>;
