export const DESKTOP_INVOKE_CHANNELS = Object.freeze({
  appVersion: "desktop:app-version",
  serverStatus: "desktop:server-status",
  protocolHandlerState: "desktop:protocol-handler-state",
  updateState: "desktop:update-state",
  updateCheck: "desktop:update-check",
  updateInstall: "desktop:update-install",
  themeState: "theme:state",
  themeSystemState: "theme:system-state",
  themeSet: "theme:set",
  themeDesignSet: "theme:design-set",
  compactModeState: "compact-mode:state",
  compactModeSet: "compact-mode:set",
  devicePreferencesState: "device-preferences:state",
  devicePreferencesUpdate: "device-preferences:update",
  aiChannelState: "ai-channel:state",
  aiChannelStart: "ai-channel:start",
  aiChannelWorkspaceChoose: "ai-channel:workspace-choose",
  aiChannelSessionNew: "ai-channel:session-new",
  aiChannelPromptSend: "ai-channel:prompt-send",
  aiChannelPromptCancel: "ai-channel:prompt-cancel",
  aiChannelPermissionRespond: "ai-channel:permission-respond",
  sessionState: "chat:session-state",
  sessionRetry: "chat:session-retry",
  sessionAuthCapabilities: "chat:session-auth-capabilities",
  sessionStartAuthKit: "chat:session-start-authkit",
  sessionRequestMagicLink: "chat:session-request-magic-link",
  sessionSignOut: "chat:session-sign-out",
  cacheCryptoInitialize: "cache:crypto-initialize",
  cacheCryptoEncrypt: "cache:crypto-encrypt",
  cacheCryptoDecrypt: "cache:crypto-decrypt",
  cacheCryptoReset: "cache:crypto-reset",
  workspaceBootstrap: "workspace:bootstrap",
  workspaceMembersList: "workspace:members-list",
  workspaceProfileUpdate: "workspace:profile-update",
  workspaceAdminCommunicationPaths: "workspace:admin-communication-paths",
  workspaceAgentEnrollmentsList: "workspace:agent-enrollments-list",
  workspaceAgentEnrollmentReview: "workspace:agent-enrollment-review",
  workspaceAgentEnrollmentCancel: "workspace:agent-enrollment-cancel",
  workspaceConversationsList: "workspace:conversations-list",
  workspaceMessagesList: "workspace:messages-list",
  workspaceMessageGet: "workspace:message-get",
  workspaceMessageRetract: "workspace:message-retract",
  workspaceMessageThread: "workspace:message-thread",
  workspaceReactionsList: "workspace:reactions-list",
  workspaceReactionAdd: "workspace:reaction-add",
  workspaceReactionRemove: "workspace:reaction-remove",
  workspaceMessageSearch: "workspace:message-search",
  workspaceAttachmentsList: "workspace:attachments-list",
  workspaceConversationFilesList: "workspace:conversation-files-list",
  workspaceFileUpload: "workspace:file-upload",
  workspaceFileOpen: "workspace:file-open",
  workspaceTasksList: "workspace:tasks-list",
  workspaceMyTasksList: "workspace:my-tasks-list",
  workspaceTaskCreate: "workspace:task-create",
  workspaceTaskUpdate: "workspace:task-update",
  workspaceTaskMove: "workspace:task-move",
  workspaceMessageSend: "workspace:message-send",
  workspaceChannelCreate: "workspace:channel-create",
  workspaceChannelArchive: "workspace:channel-archive",
  workspaceChannelMembersList: "workspace:channel-members-list",
  workspaceChannelMemberUpsert: "workspace:channel-member-upsert",
  workspaceChannelMemberRemove: "workspace:channel-member-remove",
  workspaceDirectCreate: "workspace:direct-create",
  workspaceReadAdvance: "workspace:read-advance",
  workspaceSync: "workspace:sync",
  workspaceRealtimeStart: "workspace:realtime-start",
  workspaceRealtimeActivate: "workspace:realtime-activate",
  workspaceRealtimeStop: "workspace:realtime-stop",
  workspaceRealtimeAcknowledge: "workspace:realtime-acknowledge",
  workspaceActivityTypingSet: "workspace:activity-typing-set",
  realtimeStateGet: "realtime:state-get",
  notificationContext: "notification:context",
  notificationActivityUpdate: "notification:activity-update",
  notificationActionsDrain: "notification:actions-drain",
  notificationActionAcknowledge: "notification:action-acknowledge",
  notificationState: "notification:state",
  notificationPreferenceSet: "notification:preference-set",
  notificationCapabilityRefresh: "notification:capability-refresh",
  notificationCaptureActivate: "notification:capture-activate",
} as const);

export const DESKTOP_INITIAL_CHANNELS = Object.freeze({
  automationHeadless: "desktop:automation-headless",
} as const);

export const DESKTOP_PUSH_CHANNELS = Object.freeze({
  updateChanged: "desktop:update-changed",
  themeChanged: "theme:changed",
  compactModeChanged: "compact-mode:changed",
  devicePreferencesChanged: "device-preferences:changed",
  aiChannelChanged: "ai-channel:changed",
  sessionChanged: "chat:session-changed",
  workspaceEvent: "workspace:event",
  workspaceActivity: "workspace:activity",
  realtimeStateChanged: "realtime:state-changed",
  notificationStateChanged: "notification:state-changed",
  notificationAction: "desktop:notification-action",
} as const);

export const DESKTOP_CHANNELS = Object.freeze({
  ...DESKTOP_INVOKE_CHANNELS,
  ...DESKTOP_INITIAL_CHANNELS,
  ...DESKTOP_PUSH_CHANNELS,
});

export type DesktopPushChannel = (typeof DESKTOP_PUSH_CHANNELS)[keyof typeof DESKTOP_PUSH_CHANNELS];
