declare const __HYPE_COMMS_API_ORIGIN__: string;
declare const __HYPE_COMMS_MACOS_NATIVE_NOTIFICATION_EVIDENCE_ENABLED__: boolean;
declare const __HYPE_COMMS_NATIVE_NOTIFICATIONS_ENABLED__: boolean;
declare const __HYPE_COMMS_PRODUCTION_CSP__: string;
